// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcDgTQIZLQL1ZSO7XmS-hsxLmDB7CM0pg',
    appId: '1:241361616971:web:880029adb2c598b32a4dce',
    messagingSenderId: '241361616971',
    projectId: 'skenteas',
    authDomain: 'skenteas.firebaseapp.com',
    storageBucket: 'skenteas.firebasestorage.app',
    measurementId: 'G-T0783BVRTC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRbgdEGn5Ghh61yDrjYlq9gxs4mIFoxcg',
    appId: '1:241361616971:android:ccf6ccabd86ef76b2a4dce',
    messagingSenderId: '241361616971',
    projectId: 'skenteas',
    storageBucket: 'skenteas.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcDgTQIZLQL1ZSO7XmS-hsxLmDB7CM0pg',
    appId: '1:241361616971:web:5eed008a4047899b2a4dce',
    messagingSenderId: '241361616971',
    projectId: 'skenteas',
    authDomain: 'skenteas.firebaseapp.com',
    storageBucket: 'skenteas.firebasestorage.app',
    measurementId: 'G-P5MRB8C59J',
  );
}
